const { Subject, Connector, Descphrase, Wild, Terminator } = require('./statusphraseobjs.js');

exports.standard_list = [
  new Subject("Triangle"),
  new Subject("Box"),
  new Subject("Kingdom"),
  new Subject("Ocean"),
  new Subject("Jimmy Sprocket"),
  new Subject("Ridgelaw"),
  new Subject("Stone"),
  new Subject("Tree"),
  new Subject("Rocketship"),
  new Subject("Castle"),
  new Subject("Man"),
  new Subject("Smuggler"),
  new Subject("Wizard"),
  new Subject("Knight"),
  new Subject("Barbarian"),
  new Subject("Lizard"),
  new Connector("Visits The"),
  new Connector("Fights The"),
  new Connector("Murders The"),
  new Connector("Hates The"),
  new Connector("Is Stolen By The"),
  new Connector("And The"),
  new Connector("Is Not"),
  new Connector("Is"),
  new Descphrase("Shitty"),
  new Descphrase("Cursed"),
  new Descphrase("Musclebound"),
  new Descphrase("Diseased"),
  new Descphrase("Tiny"),
  new Descphrase("Notably Mundane"),
  new Descphrase("Holiday Themed"),
  new Descphrase("Haunted"),
  new Descphrase("French Canadian"),
  new Descphrase("Dutch"),
  new Terminator("Uncut"),
  new Terminator("Professional"),
  new Terminator("Reloaded"),
  new Terminator("Deluxe Edition"),
  new Terminator("In Shocking 3D"),
];

exports.relevant_start_statuses = [
  'PLAYING',
  'WATCHING',
  'LISTENING',
  'COMPETING'
];